const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const EMPTY_CART = "EMPTY_CART";
const PRODUCT_LIST = "PRODUCT_LIST";
const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
const SEARCH = "SEARCH";
export {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  EMPTY_CART,
  PRODUCT_LIST,
  SET_PRODUCT_LIST,
  SEARCH
};
